import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => { await page.goto('/e2e/fixtures/command-palette.html') })
const dialogName = 'Search commands'

test('overlay focuses, traps Tab, preserves state and restores focus on dismissal', async ({ page }) => {
  const trigger = page.locator('#trigger')
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: dialogName, exact: true })
  const input = dialog.getByRole('combobox')
  await expect(input).toBeFocused()
  await expect(page.locator('body')).toHaveCSS('overflow', 'hidden')
  await input.press('Shift+Tab')
  await expect(dialog.getByRole('button', { name: 'Replace results' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(input).toBeFocused()
  await input.fill('Command 0-2')
  await input.press('Enter')
  await expect(page.locator('#result')).toHaveText('0-2 / 1 / 0')
  await input.press('Escape')
  await expect(dialog).not.toBeVisible()
  await expect(trigger).toBeFocused()
  await expect(page.locator('body')).not.toHaveCSS('overflow', 'hidden')
  await trigger.click()
  await expect(input).toHaveValue('Command 0-2')
  await dialog.getByRole('button', { name: 'Close command palette', exact: true }).click()
  await expect(page.locator('#result')).toHaveText('0-2 / 1 / 2')
  await expect(trigger).toBeFocused()
})

test('keyboard and pointer activate once, disabled rows skip, IME and forms are safe', async ({ page }) => {
  const input = page.getByRole('combobox', { name: 'Inline first' })
  await input.focus()
  await input.press('ArrowDown')
  await input.press('Enter')
  await expect(page.locator('#result')).toHaveText('/ 1 / 0')
  const first = page.locator('.nyx-command-palette').filter({ has: input })
  await expect(first.locator('[aria-selected="true"]')).toHaveAttribute('aria-label', 'Command 0-2')
  await first.getByRole('option', { name: 'Command 0-1', exact: true }).click({ force: true })
  await expect(page.locator('#result')).toHaveText('/ 1 / 0')
  await first.getByRole('option', { name: 'Command 0-2', exact: true }).click()
  await expect(input).toBeFocused()
  await expect(page.locator('#result')).toHaveText('/ 2 / 0')
  await input.dispatchEvent('compositionstart')
  await input.press('Enter')
  await input.press('ArrowDown')
  await input.press('Escape')
  await expect(page.locator('#result')).toHaveText('/ 2 / 0')
  await input.dispatchEvent('compositionend')
  await input.fill('no matches anywhere')
  await input.press('Enter')
  await expect(page.locator('#result')).toHaveText('/ 2 / 0')
  await input.press('Tab')
  await expect(page.getByRole('button', { name: 'Inline footer' })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('combobox', { name: 'Inline second' })).toBeFocused()
})

test('instances have unique IDs, independent queries and bounded result scrolling', async ({ page }) => {
  const first = page.getByRole('combobox', { name: 'Inline first' })
  const second = page.getByRole('combobox', { name: 'Inline second' })
  expect(await first.getAttribute('aria-controls')).not.toBe(await second.getAttribute('aria-controls'))
  await first.fill('Command 2')
  await expect(second).toHaveValue('')
  await first.fill('')
  await first.press('Alt+End')
  const active = await first.getAttribute('aria-activedescendant')
  expect(await page.locator(`[id="${active}"]`).getAttribute('aria-label')).toBe('Command 4-19')
  const viewport = first.locator('xpath=../..').locator('.nyx-command-palette__viewport')
  await expect.poll(() => viewport.evaluate(el => el.scrollTop)).toBeGreaterThan(0)
  await expect(first).toBeFocused()
})

test('backdrop requires a press and release outside, and composition Escape cannot close', async ({ page }) => {
  await page.locator('#trigger').click()
  const dialog = page.getByRole('dialog', { name: dialogName, exact: true })
  const input = dialog.getByRole('combobox')
  await input.dispatchEvent('compositionstart')
  await input.press('Escape')
  await expect(dialog).toBeVisible()
  await input.dispatchEvent('compositionend')
  const box = await input.boundingBox()
  await page.mouse.move(box!.x + 10, box!.y + 10)
  await page.mouse.down()
  await page.mouse.move(2, 2)
  await page.mouse.up()
  await expect(dialog).toBeVisible()
  await page.mouse.click(2, 2)
  await expect(dialog).not.toBeVisible()
  await expect(page.locator('#result')).toHaveText('/ 0 / 1')
})

test('parent closure, mode switching and unmount release scroll without dismissal echoes', async ({ page }) => {
  await page.evaluate(() => document.body.style.setProperty('overflow', 'scroll', 'important'))
  await page.locator('#trigger').click()
  const dialog = page.getByRole('dialog', { name: dialogName, exact: true })
  await dialog.getByRole('button', { name: 'Close from parent' }).click()
  await expect(page.locator('#trigger')).toBeFocused()
  await expect(page.locator('body')).toHaveCSS('overflow', 'scroll')
  await expect(page.locator('#result')).toHaveText('/ 0 / 0')
  await page.locator('#trigger').click()
  await dialog.getByRole('button', { name: 'Switch mode' }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.locator('body')).toHaveCSS('overflow', 'scroll')
  await page.getByRole('button', { name: 'Switch mode' }).click()
  await expect(dialog).toBeVisible()
  await dialog.getByRole('button', { name: 'Unmount', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await expect(page.locator('body')).toHaveCSS('overflow', 'scroll')
  expect(await page.evaluate(() => document.body.style.getPropertyPriority('overflow'))).toBe('important')
})

test('stacked palettes close only the topmost and retain the shared scroll lock', async ({ page }) => {
  await page.locator('#trigger').click()
  const first = page.getByRole('dialog', { name: dialogName, exact: true })
  await first.getByRole('button', { name: 'Second overlay' }).click()
  const second = page.getByRole('dialog', { name: 'Second overlay', exact: true })
  await second.getByRole('combobox').press('Escape')
  await expect(second).not.toBeVisible()
  await expect(first).toBeVisible()
  await expect(first.getByRole('button', { name: 'Second overlay' })).toBeFocused()
  await expect(page.locator('body')).toHaveCSS('overflow', 'hidden')
  await page.keyboard.press('Escape')
  await expect(first).not.toBeVisible()
  await expect(page.locator('#trigger')).toBeFocused()
})

test('disabled opening, remote replacements, and narrow layouts remain usable', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 640 })
  await page.getByRole('button', { name: 'Toggle disabled' }).click()
  await page.locator('#trigger').click()
  const dialog = page.getByRole('dialog', { name: dialogName, exact: true })
  await expect(dialog.getByRole('button', { name: 'Close command palette', exact: true })).toBeFocused()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)
  await dialog.getByRole('button', { name: 'Close command palette', exact: true }).click()
  const remote = page.getByRole('combobox', { name: 'Search commands', exact: true })
  await remote.fill('a')
  await page.waitForTimeout(220)
  await remote.fill('ab')
  await expect(page.getByRole('option', { name: 'Server result for ab' })).toBeVisible()
  await page.waitForTimeout(1000)
  await expect(page.getByRole('option', { name: 'Server result for ab' })).toBeVisible()
  await remote.press('Enter')
  await expect(page.getByText(/Selected: remote-ab/)).toBeVisible()
})


test('unmount restores a connected opener and tolerates a removed opener', async ({ page }) => {
  await page.locator('#trigger').click()
  await page.getByRole('button', { name: 'Unmount', exact: true }).click()
  await expect(page.locator('#trigger')).toBeFocused()
  await expect(page.locator('body')).not.toHaveCSS('overflow', 'hidden')
  await page.reload()
  await page.locator('#trigger').click()
  await page.locator('#trigger').evaluate(el => el.remove())
  await page.getByRole('button', { name: 'Unmount', exact: true }).click()
  await expect(page.locator('body')).not.toHaveCSS('overflow', 'hidden')
})


test('opening with a distant selection scrolls only the result viewport', async ({ page }) => {
  await page.getByRole('button', { name: 'Open with selection' }).click()
  const dialog = page.getByRole('dialog', { name: dialogName, exact: true })
  const active = dialog.locator('[data-active="true"]')
  await expect(active).toHaveAttribute('aria-label', 'Command 4-19')
  const viewport = dialog.locator('.nyx-command-palette__viewport')
  await expect.poll(() => viewport.evaluate(el => el.scrollTop)).toBeGreaterThan(0)
  const rowBox = await active.boundingBox()
  const listBox = await viewport.boundingBox()
  expect(rowBox!.y + rowBox!.height).toBeLessThanOrEqual(listBox!.y + listBox!.height + 1)
  await expect(dialog.getByRole('combobox')).toBeFocused()
  expect(await page.evaluate(() => scrollY)).toBe(0)
})
