import { test, expect } from '@playwright/test'

for (const mode of ['dark', 'light']) {
  test(`safe narrow rendering, keyboard and stable controls in ${mode} mode`, async ({ page }) => {
    const requests: string[] = []
    page.on('request', request => { if (request.url().includes('example.com')) requests.push(request.url()) })
    await page.goto('/e2e/fixtures/markdown.html')
    await page.setViewportSize({ width: 375, height: 800 })
    await page.evaluate(mode => document.documentElement.setAttribute('data-nyx-mode', mode), mode)
    const answer = page.locator('#answer')
    await expect(answer.locator('img, script, svg, iframe')).toHaveCount(0)
    const citation = page.getByRole('button', { name: 'Jump to rehearsal message' })
    await citation.focus()
    await page.keyboard.press('Enter')
    await expect(page.locator('#clicks')).toHaveText('1')
    await page.locator('#append').evaluate((button: HTMLButtonElement) => button.click())
    await expect(citation).toBeFocused()
    await page.keyboard.press('Space')
    await expect(page.locator('#clicks')).toHaveText('2')
    await expect(page.locator('#independent')).toHaveText('Independent [[p1:m2]]')
    const pre = answer.locator('pre').first()
    await pre.focus()
    await page.keyboard.press('ArrowRight')
    await expect.poll(() => pre.evaluate(el => el.scrollLeft)).toBeGreaterThan(0)
    const scroll = await pre.evaluate(el => el.scrollLeft)
    await page.locator('#append').evaluate((button: HTMLButtonElement) => button.click())
    await expect(pre).toBeFocused()
    expect(await pre.evaluate(el => el.scrollLeft)).toBeGreaterThanOrEqual(scroll)
    const table = answer.getByRole('region', { name: 'Markdown table' })
    await table.focus()
    await page.keyboard.press('ArrowRight')
    await expect.poll(() => table.evaluate(el => el.scrollLeft)).toBeGreaterThan(0)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await expect(answer.locator('a')).toHaveAttribute('rel', 'noopener noreferrer')
    expect(requests).toEqual([])
    await page.locator('#replace').click()
    await expect(answer).toHaveText('Replacement answer')
    await page.locator('#clear').click()
    await expect(answer).toBeEmpty()
  })
}

test('long-answer rendering leaves typing responsive', async ({ page }) => {
  await page.goto('/e2e/fixtures/markdown.html')
  await page.locator('#benchmark').click()
  await page.getByRole('textbox', { name: 'Typing check' }).fill('Still responsive')
  await expect(page.locator('#measurement')).not.toBeEmpty()
  await expect(page.getByRole('textbox', { name: 'Typing check' })).toHaveValue('Still responsive')
  const result = JSON.parse(await page.locator('#measurement').innerText())
  console.log('NyxMarkdown synthetic benchmark', result)
  expect(result.characters).toBeGreaterThan(10000)
  expect(result.maxMs).toBeLessThan(2000)
})
